version: '3.8'

volumes:
  deal_tracker_backend_local_postgres_data: {}

services:

  postgres:
    image: "postgres:14-alpine"
    container_name: deal_tracker_backend_local_postgres
    restart: unless-stopped
    volumes:
      - deal_tracker_backend_local_postgres_data:/var/lib/postgresql/data
    networks:
      - postgresnet
    env_file:
      - ./.envs/.local/.postgres

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: deal_tracker_backend_local_django
    container_name: deal_tracker_backend_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    networks:
      - postgresnet
      - webnet
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start



networks:
  postgresnet:
  webnet:
