# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']
skip-string-normalization = true
skip-magic-trailing-comma = true
exclude = '/migrations/'


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = [
    "apps",
    "config",
]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
use_parentheses = true
skip = [".venv/", "migrations", ".history"]
skip_gitignore = true
