# Generated by Django 4.2.2 on 2023-06-30 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Драгоценный камень',
                'verbose_name_plural': 'Драгоценные камни',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(verbose_name='Итоговая сумма сделки')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Общее количество камней')),
                ('date', models.DateTimeField(unique=True, verbose_name='Дата и время сделки')),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='deals',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Клиент',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deals',
                        to='deals.gem',
                        verbose_name='Драгоценный камень',
                    ),
                ),
            ],
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки', 'ordering': ('-date',)},
        ),
    ]
